### ISSUE TITLE
Frontend: Footer showing default (0) values

### ISSUE THREAD

**Issue by Saibamen** [timiimit/UT4MasterServer#124]
FYI: @caseyswilliams 

Previously we had `onMounted(ServerStore.fetchGameServers);` in https://github.com/timiimit/UT4MasterServer/blob/master/UT4MasterServer.Web/src/components/Footer.vue

### Repro steps

1. Open new web browser tab
2. Go to any frontend page, except Servers, for example https://ut4.timiimit.com/

### Expected Results

Footer shows current values without manually clicking on Refresh button or going into `/Servers` page

### Actual Results

Footer always shows default values (0). Need to click on "Refresh" button or go to `/Servers` page

**Comment by caseyswilliams** [comment]
This actually updates automatically after 30 seconds, not only after refresh button or hitting servers page, but yeah it should fetch immediately, too. Fixed in PR #128
