### ISSUE TITLE
Containers grow in size

### ISSUE THREAD

**Issue by timiimit** [timiimit/UT4MasterServer#136]
The longer containers are running the more storage space they waste. One or more containers fill up some file unneccesserily.

**Comment by Saibamen** [comment]
Any news after https://github.com/timiimit/UT4MasterServer/pull/143 (https://github.com/timiimit/UT4MasterServer/issues/137)?

**Comment by timiimit** [comment]
It seems to be better now. But why would log size make container larger when logs are in a persistent volume which is outside of any container?

**Comment by timiimit** [comment]
Docker still stores console (stdout, stderr) logs that container makes. That is why storage was going up.
